"""initial

Revision ID: 032881aa361a
Revises: 
Create Date: 2026-06-20 23:03:47.707690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '032881aa361a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('github_access_token', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_github_id'), 'user', ['github_id'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('repository',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('github_repo_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('clone_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('default_branch', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_full_name'), 'repository', ['full_name'], unique=False)
    op.create_index(op.f('ix_repository_github_repo_id'), 'repository', ['github_repo_id'], unique=True)
    op.create_index('ix_repository_owner_full_name', 'repository', ['owner_id', 'full_name'], unique=False)
    op.create_index(op.f('ix_repository_owner_id'), 'repository', ['owner_id'], unique=False)
    op.create_table('task',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('repository_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('target_branch', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('pull_request_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('pull_request_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_repository_id'), 'task', ['repository_id'], unique=False)
    op.create_index('ix_task_repository_status', 'task', ['repository_id', 'status'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    op.create_index(op.f('ix_task_user_id'), 'task', ['user_id'], unique=False)
    op.create_index('ix_task_user_status', 'task', ['user_id', 'status'], unique=False)
    op.create_table('attempt',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'running'"), nullable=False),
    sa.Column('branch_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('plan_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('patch_diff', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('build_log', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('test_log', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reflection_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=4096), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempt_status'), 'attempt', ['status'], unique=False)
    op.create_index(op.f('ix_attempt_task_id'), 'attempt', ['task_id'], unique=False)
    op.create_index('ix_attempt_task_number', 'attempt', ['task_id', 'attempt_number'], unique=True)
    op.create_index('ix_attempt_task_status', 'attempt', ['task_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attempt_task_status', table_name='attempt')
    op.drop_index('ix_attempt_task_number', table_name='attempt')
    op.drop_index(op.f('ix_attempt_task_id'), table_name='attempt')
    op.drop_index(op.f('ix_attempt_status'), table_name='attempt')
    op.drop_table('attempt')
    op.drop_index('ix_task_user_status', table_name='task')
    op.drop_index(op.f('ix_task_user_id'), table_name='task')
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index('ix_task_repository_status', table_name='task')
    op.drop_index(op.f('ix_task_repository_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_repository_owner_id'), table_name='repository')
    op.drop_index('ix_repository_owner_full_name', table_name='repository')
    op.drop_index(op.f('ix_repository_github_repo_id'), table_name='repository')
    op.drop_index(op.f('ix_repository_full_name'), table_name='repository')
    op.drop_table('repository')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_github_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
