"""Shared Pydantic Schemas for the Coder Agent.

Defines payloads and response structures for code generation, file changes,
unified diffs, and API requests/responses.
"""

from typing import Dict, List, Literal, Optional
from pydantic import BaseModel, Field

from app.schemas.planner import ImplementationPlan


class SingleFileGenerationResult(BaseModel):
    """Lightweight schema for single-file LLM code generation response."""

    change_type: Literal["create", "modify", "delete"] = Field(
        ...,
        description="Type of change applied to this file: 'create', 'modify', or 'delete'",
    )
    generated_content: Optional[str] = Field(
        default=None,
        description="Complete, non-truncated generated content for created or modified files (None for deleted files)",
    )
    explanation: str = Field(
        ...,
        description="Detailed technical explanation of what was changed, created, or deleted in this specific file and why",
    )


class CodingSummaryResult(BaseModel):
    """Lightweight schema for final LLM summarization response."""

    summary: str = Field(
        ...,
        description="High-level executive summary of all implemented code changes",
    )
    reasoning: str = Field(
        ...,
        description="Architectural and implementation reasoning explaining how code satisfies the ImplementationPlan",
    )



class GeneratedFile(BaseModel):
    """Represents a single file created, modified, or deleted by the Coder Agent."""

    path: str = Field(..., description="Relative repository file path (e.g. 'src/auth/jwt.py')")
    change_type: Literal["create", "modify", "delete"] = Field(
        ...,
        description="Type of change applied to this file: 'create', 'modify', or 'delete'",
    )
    original_content: Optional[str] = Field(
        default=None,
        description="Original text content of the file prior to modification (None for created files)",
    )
    generated_content: Optional[str] = Field(
        default=None,
        description="Complete, non-truncated generated content for created or modified files (None for deleted files)",
    )
    explanation: str = Field(
        ...,
        description="Detailed technical explanation of what was changed, created, or deleted and why",
    )
    unified_diff: Optional[str] = Field(
        default=None,
        description="Standard unified diff representation comparing original_content vs generated_content",
    )


class CodeChange(BaseModel):
    """Lightweight representation of a single file code change."""

    path: str = Field(..., description="Relative file path")
    change_type: Literal["create", "modify", "delete"] = Field(..., description="Change type")
    explanation: str = Field(..., description="Summary explanation of change")


class CodingResult(BaseModel):
    """Output result payload produced by the Coder Agent execution."""

    summary: str = Field(
        ...,
        description="High-level executive summary of all implemented code changes",
    )
    generated_files: List[GeneratedFile] = Field(
        default_factory=list,
        description="List of all created, modified, or deleted file objects",
    )
    unified_diffs: Dict[str, str] = Field(
        default_factory=dict,
        description="Map of relative file paths to their unified diff patch strings",
    )
    reasoning: str = Field(
        ...,
        description="Architectural and implementation reasoning explaining how code satisfies the ImplementationPlan",
    )
    warnings: List[str] = Field(
        default_factory=list,
        description="List of non-fatal warnings (e.g., missing original files, binary files skipped, size limits hit)",
    )


class CoderRequest(BaseModel):
    """API request payload for invoking the Coder Agent."""

    implementation_plan: Optional[ImplementationPlan] = Field(
        default=None,
        description="Optional explicit ImplementationPlan object. If omitted, uses the latest plan generated by the Planner.",
    )
    user_prompt_override: Optional[str] = Field(
        default=None,
        description="Optional additional natural language coding instructions or hints.",
    )
