"""Schemas for the Orchestrator Service (Phase 12).

Defines:
- PipelineIteration: Schema representing the inputs/outputs of a single iteration loop.
- FinalExecutionResult: Schema representing the complete execution outcome of the autonomous pipeline.
"""

from typing import List, Optional
from pydantic import BaseModel, Field

from app.schemas.coder import CodingResult
from app.schemas.reflector import ReflectionResult
from app.schemas.tester import TestResult


class PipelineIteration(BaseModel):
    """Represents the inputs, execution results, and reflection for a single iteration attempt."""

    iteration_number: int = Field(
        ...,
        description="1-indexed iteration number within the self-correction retry loop.",
    )
    coding_result: CodingResult = Field(
        ...,
        description="Code changes generated by the Coder Agent for this iteration.",
    )
    test_result: TestResult = Field(
        ...,
        description="Outcome of running validation tests inside the isolated workspace.",
    )
    reflection_result: Optional[ReflectionResult] = Field(
        default=None,
        description="Reflector Agent failure analysis guidance (None if test_result succeeded).",
    )


class FinalExecutionResult(BaseModel):
    """Final output result payload produced by the Orchestrator Service.

    Consolidates overall success status, total iteration count, final agent results,
    full iteration history, execution timing, and a deterministic summary.
    """

    success: bool = Field(
        ...,
        description="True if validation tests passed in any iteration; False if max retries reached or failure unrepairable.",
    )
    total_iterations: int = Field(
        ...,
        description="Total number of iterations executed by the pipeline loop.",
    )
    final_test_result: Optional[TestResult] = Field(
        default=None,
        description="The last TestResult produced during execution.",
    )
    final_coding_result: Optional[CodingResult] = Field(
        default=None,
        description="The final CodingResult generated during execution.",
    )
    final_reflection_result: Optional[ReflectionResult] = Field(
        default=None,
        description="The final ReflectionResult produced (if any iteration failed).",
    )
    iteration_history: List[PipelineIteration] = Field(
        default_factory=list,
        description="Ordered list of all iterations executed during the pipeline run.",
    )
    total_execution_time_ms: int = Field(
        ...,
        description="Total wall-clock execution time in milliseconds across all pipeline steps.",
    )
    summary: str = Field(
        ...,
        description="Deterministic summary describing pipeline execution outcome (no LLM).",
    )
